-- Database and schemas
CREATE DATABASE IF NOT EXISTS IMDB_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS IMDB_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS IMDB_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS IMDB_ANALYTICS.GOLD;


-- Verify
SHOW SCHEMAS IN DATABASE IMDB_ANALYTICS;

